const data = [
  {
    department: "Legal",
    company: "Oyondu",
    gender: "Male",
    language: "Oriya",
    first_name: "Clementius",
    ssn: "176-82-5491",
  },
  {
    department: "Support",
    company: "Skipfire",
    gender: "Male",
    language: "Danish",
    first_name: "Bertrand",
    ssn: "417-27-8214",
  },
  {
    department: "Training",
    company: "Skyndu",
    gender: "Bigender",
    language: "Finnish",
    first_name: "Egor",
    ssn: "583-37-8910",
  },
  {
    department: "Business Development",
    company: "Brainbox",
    gender: "Female",
    language: "Bengali",
    first_name: "Babette",
    ssn: "189-22-1605",
  },
  {
    department: "Training",
    company: "Kwilith",
    gender: "Male",
    language: "Tajik",
    first_name: "Hirsch",
    ssn: "365-21-2785",
  },
  {
    department: "Business Development",
    company: "Zava",
    gender: "Female",
    language: "Dzongkha",
    first_name: "Elle",
    ssn: "485-89-3745",
  },
  {
    department: "Support",
    company: "Topicshots",
    gender: "Male",
    language: "Bulgarian",
    first_name: "Lindon",
    ssn: "768-76-0002",
  },
  {
    department: "Support",
    company: "InnoZ",
    gender: "Male",
    language: "New Zealand Sign Language",
    first_name: "Timofei",
    ssn: "635-04-4832",
  },
  {
    department: "Product Management",
    company: "Eare",
    gender: "Female",
    language: "Luxembourgish",
    first_name: "Valentina",
    ssn: "452-09-9172",
  },
  {
    department: "Business Development",
    company: "Eamia",
    gender: "Female",
    language: "Tsonga",
    first_name: "Malory",
    ssn: "105-75-8188",
  },
  {
    department: "Business Development",
    company: "Oyope",
    gender: "Female",
    language: "Tamil",
    first_name: "Margit",
    ssn: "462-77-4092",
  },
  {
    department: "Services",
    company: "Twitterbeat",
    gender: "Male",
    language: "Kazakh",
    first_name: "Dewey",
    ssn: "180-30-2357",
  },
  {
    department: "Engineering",
    company: "Yambee",
    gender: "Male",
    language: "Khmer",
    first_name: "Vasilis",
    ssn: "144-16-7657",
  },
  {
    department: "Accounting",
    company: "Feedspan",
    gender: "Male",
    language: "Lao",
    first_name: "Perice",
    ssn: "619-12-8492",
  },
  {
    department: "Business Development",
    company: "Rhynyx",
    gender: "Male",
    language: "Greek",
    first_name: "Hayden",
    ssn: "797-74-6585",
  },
  {
    department: "Engineering",
    company: "Roodel",
    gender: "Male",
    language: "Assamese",
    first_name: "Toddy",
    ssn: "720-52-0246",
  },
  {
    department: "Sales",
    company: "Yata",
    gender: "Female",
    language: "Luxembourgish",
    first_name: "Cornelia",
    ssn: "532-65-7144",
  },
  {
    department: "Sales",
    company: "Topdrive",
    gender: "Male",
    language: "Bosnian",
    first_name: "Reinhard",
    ssn: "786-96-3584",
  },
  {
    department: "Marketing",
    company: "Dabfeed",
    gender: "Male",
    language: "Norwegian",
    first_name: "Staford",
    ssn: "660-02-6430",
  },
  {
    department: "Engineering",
    company: "Skivee",
    gender: "Male",
    language: "Dzongkha",
    first_name: "Wilmar",
    ssn: "882-70-6252",
  },
  {
    department: "Support",
    company: "Edgeclub",
    gender: "Female",
    language: "Albanian",
    first_name: "Blair",
    ssn: "174-88-9473",
  },
  {
    department: "Support",
    company: "Tanoodle",
    gender: "Male",
    language: "Bengali",
    first_name: "Scotti",
    ssn: "803-63-3058",
  },
  {
    department: "Services",
    company: "Jaxbean",
    gender: "Male",
    language: "New Zealand Sign Language",
    first_name: "Emory",
    ssn: "208-51-7930",
  },
  {
    department: "Product Management",
    company: "Edgeclub",
    gender: "Female",
    language: "Malagasy",
    first_name: "Kania",
    ssn: "237-52-5378",
  },
  {
    department: "Marketing",
    company: "Yakijo",
    gender: "Female",
    language: "Polish",
    first_name: "Lynette",
    ssn: "597-27-6564",
  },
  {
    department: "Accounting",
    company: "Aimbu",
    gender: "Male",
    language: "Tok Pisin",
    first_name: "Redd",
    ssn: "461-69-3237",
  },
  {
    department: "Engineering",
    company: "Babbleopia",
    gender: "Male",
    language: "Quechua",
    first_name: "Morse",
    ssn: "432-82-4772",
  },
  {
    department: "Business Development",
    company: "Eadel",
    gender: "Male",
    language: "Zulu",
    first_name: "Uriel",
    ssn: "140-18-1915",
  },
  {
    department: "Accounting",
    company: "BlogXS",
    gender: "Female",
    language: "Georgian",
    first_name: "Regina",
    ssn: "554-66-1027",
  },
  {
    department: "Business Development",
    company: "Livetube",
    gender: "Male",
    language: "Assamese",
    first_name: "Conney",
    ssn: "241-13-7049",
  },
  {
    department: "Marketing",
    company: "Oba",
    gender: "Male",
    language: "Italian",
    first_name: "Whitby",
    ssn: "652-10-3529",
  },
  {
    department: "Product Management",
    company: "Eayo",
    gender: "Male",
    language: "Northern Sotho",
    first_name: "Ferdinand",
    ssn: "757-05-1980",
  },
  {
    department: "Business Development",
    company: "Vimbo",
    gender: "Non-binary",
    language: "Albanian",
    first_name: "Merridie",
    ssn: "542-34-9510",
  },
  {
    department: "Sales",
    company: "Layo",
    gender: "Female",
    language: "Portuguese",
    first_name: "Selie",
    ssn: "345-85-4125",
  },
  {
    department: "Support",
    company: "Quinu",
    gender: "Female",
    language: "Malagasy",
    first_name: "Ibbie",
    ssn: "443-17-5140",
  },
  {
    department: "Accounting",
    company: "Pixoboo",
    gender: "Male",
    language: "Hiri Motu",
    first_name: "Granny",
    ssn: "289-63-0668",
  },
  {
    department: "Business Development",
    company: "Skidoo",
    gender: "Female",
    language: "Polish",
    first_name: "Fenelia",
    ssn: "429-22-3651",
  },
  {
    department: "Marketing",
    company: "Browsezoom",
    gender: "Female",
    language: "Telugu",
    first_name: "Colline",
    ssn: "394-13-4968",
  },
  {
    department: "Marketing",
    company: "JumpXS",
    gender: "Female",
    language: "Finnish",
    first_name: "Drusie",
    ssn: "492-62-8560",
  },
  {
    department: "Research and Development",
    company: "Quatz",
    gender: "Female",
    language: "Fijian",
    first_name: "Darcie",
    ssn: "513-37-4874",
  },
  {
    department: "Human Resources",
    company: "Minyx",
    gender: "Male",
    language: "Marathi",
    first_name: "Byrann",
    ssn: "621-13-4787",
  },
  {
    department: "Services",
    company: "Zazio",
    gender: "Female",
    language: "Bosnian",
    first_name: "Ebba",
    ssn: "184-35-0146",
  },
  {
    department: "Product Management",
    company: "Bluejam",
    gender: "Male",
    language: "Japanese",
    first_name: "Ty",
    ssn: "754-21-0657",
  },
  {
    department: "Business Development",
    company: "Skipfire",
    gender: "Genderfluid",
    language: "Arabic",
    first_name: "Kylila",
    ssn: "423-10-3538",
  },
  {
    department: "Services",
    company: "Oyope",
    gender: "Male",
    language: "Haitian Creole",
    first_name: "Harman",
    ssn: "126-22-6002",
  },
  {
    department: "Product Management",
    company: "Buzzbean",
    gender: "Genderfluid",
    language: "Dzongkha",
    first_name: "Darsie",
    ssn: "737-74-8575",
  },
  {
    department: "Product Management",
    company: "Gabspot",
    gender: "Male",
    language: "Luxembourgish",
    first_name: "Kilian",
    ssn: "355-43-7600",
  },
  {
    department: "Support",
    company: "Wikivu",
    gender: "Male",
    language: "Khmer",
    first_name: "Dael",
    ssn: "134-12-4183",
  },
  {
    department: "Services",
    company: "Mynte",
    gender: "Male",
    language: "Amharic",
    first_name: "Roy",
    ssn: "125-29-0710",
  },
  {
    department: "Human Resources",
    company: "Realcube",
    gender: "Male",
    language: "Macedonian",
    first_name: "Fairfax",
    ssn: "597-66-8659",
  },
  {
    department: "Training",
    company: "Gigaclub",
    gender: "Male",
    language: "Hindi",
    first_name: "Florian",
    ssn: "348-34-4580",
  },
  {
    department: "Product Management",
    company: "Dynava",
    gender: "Male",
    language: "Lao",
    first_name: "Damiano",
    ssn: "650-24-1426",
  },
  {
    department: "Sales",
    company: "Shufflester",
    gender: "Male",
    language: "Dari",
    first_name: "Maxie",
    ssn: "543-27-8321",
  },
  {
    department: "Research and Development",
    company: "Skynoodle",
    gender: "Male",
    language: "Montenegrin",
    first_name: "Walt",
    ssn: "124-18-9886",
  },
  {
    department: "Services",
    company: "Wordify",
    gender: "Male",
    language: "Icelandic",
    first_name: "Ase",
    ssn: "238-96-7160",
  },
  {
    department: "Product Management",
    company: "Linklinks",
    gender: "Female",
    language: "Albanian",
    first_name: "Penelope",
    ssn: "887-10-7024",
  },
  {
    department: "Research and Development",
    company: "Photobug",
    gender: "Male",
    language: "Indonesian",
    first_name: "Robbie",
    ssn: "658-79-4468",
  },
  {
    department: "Accounting",
    company: "Cogilith",
    gender: "Male",
    language: "Tajik",
    first_name: "Renault",
    ssn: "791-62-3249",
  },
  {
    department: "Business Development",
    company: "Layo",
    gender: "Male",
    language: "Kazakh",
    first_name: "Caryl",
    ssn: "248-38-1890",
  },
  {
    department: "Engineering",
    company: "Trudoo",
    gender: "Male",
    language: "Kashmiri",
    first_name: "Benjamen",
    ssn: "858-61-9920",
  },
  {
    department: "Product Management",
    company: "Meejo",
    gender: "Female",
    language: "Amharic",
    first_name: "Lira",
    ssn: "304-81-6880",
  },
  {
    department: "Research and Development",
    company: "Skyvu",
    gender: "Male",
    language: "Hindi",
    first_name: "Benn",
    ssn: "606-10-6001",
  },
  {
    department: "Legal",
    company: "Jaxnation",
    gender: "Female",
    language: "Lithuanian",
    first_name: "Twila",
    ssn: "542-45-5549",
  },
  {
    department: "Product Management",
    company: "Realbuzz",
    gender: "Female",
    language: "Bulgarian",
    first_name: "Ekaterina",
    ssn: "791-59-1291",
  },
  {
    department: "Support",
    company: "LiveZ",
    gender: "Female",
    language: "Azeri",
    first_name: "Wanids",
    ssn: "754-35-0887",
  },
  {
    department: "Engineering",
    company: "Topicstorm",
    gender: "Male",
    language: "Montenegrin",
    first_name: "Lance",
    ssn: "638-61-1912",
  },
  {
    department: "Training",
    company: "Fivebridge",
    gender: "Male",
    language: "Punjabi",
    first_name: "Robbert",
    ssn: "648-13-7742",
  },
  {
    department: "Product Management",
    company: "Roomm",
    gender: "Male",
    language: "Persian",
    first_name: "Vance",
    ssn: "477-34-6893",
  },
  {
    department: "Training",
    company: "Gabtype",
    gender: "Male",
    language: "Hungarian",
    first_name: "Silas",
    ssn: "114-30-4256",
  },
  {
    department: "Support",
    company: "Kayveo",
    gender: "Male",
    language: "Sotho",
    first_name: "Wildon",
    ssn: "547-47-3101",
  },
  {
    department: "Product Management",
    company: "Vimbo",
    gender: "Male",
    language: "Swati",
    first_name: "Pedro",
    ssn: "242-16-6254",
  },
  {
    department: "Training",
    company: "Thoughtbeat",
    gender: "Female",
    language: "Kurdish",
    first_name: "Jenica",
    ssn: "443-75-0424",
  },
  {
    department: "Business Development",
    company: "Eazzy",
    gender: "Male",
    language: "Māori",
    first_name: "Hill",
    ssn: "894-08-9761",
  },
  {
    department: "Legal",
    company: "Flashpoint",
    gender: "Female",
    language: "Persian",
    first_name: "Tamarra",
    ssn: "399-12-7775",
  },
  {
    department: "Human Resources",
    company: "Jaloo",
    gender: "Non-binary",
    language: "Tetum",
    first_name: "Lucilia",
    ssn: "878-39-7127",
  },
  {
    department: "Marketing",
    company: "Twitterbeat",
    gender: "Female",
    language: "Lithuanian",
    first_name: "Sal",
    ssn: "236-17-5960",
  },
  {
    department: "Legal",
    company: "Voonix",
    gender: "Male",
    language: "Afrikaans",
    first_name: "Cornell",
    ssn: "807-25-7766",
  },
  {
    department: "Support",
    company: "Yadel",
    gender: "Female",
    language: "Amharic",
    first_name: "Cathleen",
    ssn: "329-58-6959",
  },
  {
    department: "Sales",
    company: "Babbleset",
    gender: "Male",
    language: "Hindi",
    first_name: "Lion",
    ssn: "743-09-6521",
  },
  {
    department: "Training",
    company: "Youfeed",
    gender: "Female",
    language: "Dhivehi",
    first_name: "Aimil",
    ssn: "703-41-9245",
  },
  {
    department: "Accounting",
    company: "Photospace",
    gender: "Female",
    language: "Telugu",
    first_name: "Amie",
    ssn: "810-30-9295",
  },
  {
    department: "Legal",
    company: "Zoomcast",
    gender: "Male",
    language: "Afrikaans",
    first_name: "Alexei",
    ssn: "200-52-3840",
  },
  {
    department: "Support",
    company: "Vinder",
    gender: "Female",
    language: "Spanish",
    first_name: "Ardine",
    ssn: "698-31-7080",
  },
  {
    department: "Accounting",
    company: "Fivespan",
    gender: "Male",
    language: "Armenian",
    first_name: "Wayland",
    ssn: "543-94-5794",
  },
  {
    department: "Business Development",
    company: "Yodo",
    gender: "Female",
    language: "Hungarian",
    first_name: "Yalonda",
    ssn: "772-24-7633",
  },
  {
    department: "Marketing",
    company: "Kazu",
    gender: "Female",
    language: "Italian",
    first_name: "Maritsa",
    ssn: "258-10-7258",
  },
  {
    department: "Marketing",
    company: "Gabtype",
    gender: "Bigender",
    language: "Amharic",
    first_name: "Wernher",
    ssn: "209-45-1974",
  },
  {
    department: "Business Development",
    company: "Photobug",
    gender: "Male",
    language: "German",
    first_name: "Claudianus",
    ssn: "501-05-1130",
  },
  {
    department: "Accounting",
    company: "Meevee",
    gender: "Male",
    language: "Irish Gaelic",
    first_name: "Chester",
    ssn: "736-15-7002",
  },
  {
    department: "Business Development",
    company: "Brainsphere",
    gender: "Female",
    language: "Irish Gaelic",
    first_name: "Sheila-kathryn",
    ssn: "821-33-8518",
  },
  {
    department: "Business Development",
    company: "Buzzbean",
    gender: "Female",
    language: "Swedish",
    first_name: "Inna",
    ssn: "731-52-2837",
  },
  {
    department: "Legal",
    company: "Wikido",
    gender: "Male",
    language: "Gujarati",
    first_name: "Waldemar",
    ssn: "120-51-3586",
  },
  {
    department: "Sales",
    company: "Tanoodle",
    gender: "Female",
    language: "Korean",
    first_name: "Zabrina",
    ssn: "301-66-9558",
  },
  {
    department: "Research and Development",
    company: "Thoughtstorm",
    gender: "Male",
    language: "Swahili",
    first_name: "Hart",
    ssn: "397-40-3309",
  },
  {
    department: "Business Development",
    company: "Devify",
    gender: "Male",
    language: "Thai",
    first_name: "Terry",
    ssn: "546-79-4870",
  },
  {
    department: "Support",
    company: "Skiptube",
    gender: "Female",
    language: "Finnish",
    first_name: "Hester",
    ssn: "102-07-6658",
  },
  {
    department: "Business Development",
    company: "Aimbo",
    gender: "Male",
    language: "Thai",
    first_name: "Sascha",
    ssn: "820-33-9339",
  },
  {
    department: "Research and Development",
    company: "Zoombox",
    gender: "Female",
    language: "Tsonga",
    first_name: "Livia",
    ssn: "170-37-8867",
  },
  {
    department: "Human Resources",
    company: "Twitterbridge",
    gender: "Female",
    language: "Burmese",
    first_name: "Josey",
    ssn: "186-35-0911",
  },
  {
    department: "Training",
    company: "Divavu",
    gender: "Male",
    language: "Catalan",
    first_name: "Peterus",
    ssn: "329-90-6498",
  },
  {
    department: "Human Resources",
    company: "Rhybox",
    gender: "Female",
    language: "Afrikaans",
    first_name: "Timi",
    ssn: "226-16-0210",
  },
  {
    department: "Engineering",
    company: "Zoozzy",
    gender: "Female",
    language: "Arabic",
    first_name: "Whitney",
    ssn: "800-13-7323",
  },
  {
    department: "Accounting",
    company: "Blogtags",
    gender: "Male",
    language: "Tok Pisin",
    first_name: "Jeff",
    ssn: "264-40-0856",
  },
  {
    department: "Business Development",
    company: "Kimia",
    gender: "Female",
    language: "Haitian Creole",
    first_name: "Catherina",
    ssn: "850-84-1630",
  },
  {
    department: "Engineering",
    company: "Thoughtstorm",
    gender: "Male",
    language: "Tok Pisin",
    first_name: "Jesse",
    ssn: "460-59-6305",
  },
  {
    department: "Training",
    company: "Gigaclub",
    gender: "Female",
    language: "Chinese",
    first_name: "Emmeline",
    ssn: "208-94-4822",
  },
  {
    department: "Accounting",
    company: "Skimia",
    gender: "Female",
    language: "Papiamento",
    first_name: "Anastassia",
    ssn: "622-85-5131",
  },
  {
    department: "Research and Development",
    company: "Devpoint",
    gender: "Male",
    language: "Spanish",
    first_name: "Yuri",
    ssn: "466-58-8245",
  },
  {
    department: "Human Resources",
    company: "Wordpedia",
    gender: "Female",
    language: "Kannada",
    first_name: "Frannie",
    ssn: "870-27-3879",
  },
  {
    department: "Product Management",
    company: "Teklist",
    gender: "Female",
    language: "Malayalam",
    first_name: "Blanch",
    ssn: "180-28-3094",
  },
  {
    department: "Product Management",
    company: "Skyba",
    gender: "Male",
    language: "Tswana",
    first_name: "Bale",
    ssn: "161-05-4237",
  },
  {
    department: "Product Management",
    company: "Tagtune",
    gender: "Female",
    language: "Romanian",
    first_name: "Constantia",
    ssn: "434-46-5569",
  },
  {
    department: "Training",
    company: "Twitterworks",
    gender: "Male",
    language: "Persian",
    first_name: "Teddie",
    ssn: "623-62-2224",
  },
  {
    department: "Human Resources",
    company: "Yadel",
    gender: "Female",
    language: "Georgian",
    first_name: "Elfie",
    ssn: "866-89-1613",
  },
  {
    department: "Legal",
    company: "Devshare",
    gender: "Male",
    language: "Amharic",
    first_name: "Clim",
    ssn: "803-83-4142",
  },
  {
    department: "Legal",
    company: "Linkbridge",
    gender: "Female",
    language: "Chinese",
    first_name: "Elfrieda",
    ssn: "632-32-0624",
  },
  {
    department: "Accounting",
    company: "Skalith",
    gender: "Male",
    language: "Luxembourgish",
    first_name: "Willey",
    ssn: "750-18-6419",
  },
  {
    department: "Engineering",
    company: "Youbridge",
    gender: "Male",
    language: "Catalan",
    first_name: "Rodrick",
    ssn: "218-19-0178",
  },
  {
    department: "Human Resources",
    company: "Mymm",
    gender: "Male",
    language: "Punjabi",
    first_name: "Evin",
    ssn: "521-07-3546",
  },
  {
    department: "Support",
    company: "Brightbean",
    gender: "Female",
    language: "Pashto",
    first_name: "Karrah",
    ssn: "846-24-6861",
  },
  {
    department: "Training",
    company: "Livetube",
    gender: "Female",
    language: "Chinese",
    first_name: "Nelie",
    ssn: "342-93-4035",
  },
  {
    department: "Services",
    company: "Miboo",
    gender: "Female",
    language: "Swati",
    first_name: "Odella",
    ssn: "673-16-3416",
  },
  {
    department: "Product Management",
    company: "Photojam",
    gender: "Female",
    language: "Catalan",
    first_name: "Stoddard",
    ssn: "233-77-6413",
  },
  {
    department: "Services",
    company: "Topiczoom",
    gender: "Female",
    language: "Hebrew",
    first_name: "Colline",
    ssn: "472-43-9977",
  },
  {
    department: "Accounting",
    company: "Devify",
    gender: "Male",
    language: "Malayalam",
    first_name: "Reuben",
    ssn: "402-62-5107",
  },
  {
    department: "Research and Development",
    company: "Twitterworks",
    gender: "Female",
    language: "Kannada",
    first_name: "Tessa",
    ssn: "788-56-5726",
  },
  {
    department: "Training",
    company: "Topiczoom",
    gender: "Female",
    language: "Gagauz",
    first_name: "Aubree",
    ssn: "411-76-1369",
  },
  {
    department: "Training",
    company: "Quinu",
    gender: "Male",
    language: "Northern Sotho",
    first_name: "Tynan",
    ssn: "390-24-1976",
  },
  {
    department: "Product Management",
    company: "Kwideo",
    gender: "Male",
    language: "Ndebele",
    first_name: "Pace",
    ssn: "857-21-8575",
  },
  {
    department: "Support",
    company: "Zoombox",
    gender: "Male",
    language: "Italian",
    first_name: "Winfred",
    ssn: "636-67-2582",
  },
  {
    department: "Human Resources",
    company: "Dabtype",
    gender: "Male",
    language: "Tswana",
    first_name: "Devy",
    ssn: "389-87-7584",
  },
  {
    department: "Research and Development",
    company: "Demizz",
    gender: "Male",
    language: "Sotho",
    first_name: "Merle",
    ssn: "850-46-2810",
  },
  {
    department: "Services",
    company: "Devbug",
    gender: "Female",
    language: "Japanese",
    first_name: "Saundra",
    ssn: "139-23-4099",
  },
  {
    department: "Product Management",
    company: "Abatz",
    gender: "Male",
    language: "Catalan",
    first_name: "Bentlee",
    ssn: "791-44-2223",
  },
  {
    department: "Marketing",
    company: "Kwilith",
    gender: "Male",
    language: "Belarusian",
    first_name: "Ari",
    ssn: "801-45-1386",
  },
  {
    department: "Training",
    company: "Vimbo",
    gender: "Female",
    language: "Hiri Motu",
    first_name: "Emelina",
    ssn: "275-96-2714",
  },
  {
    department: "Services",
    company: "Skiptube",
    gender: "Male",
    language: "Gagauz",
    first_name: "Patty",
    ssn: "748-89-3696",
  },
  {
    department: "Marketing",
    company: "Twimbo",
    gender: "Genderqueer",
    language: "Afrikaans",
    first_name: "Darcee",
    ssn: "153-10-9370",
  },
  {
    department: "Services",
    company: "Yodo",
    gender: "Genderqueer",
    language: "Macedonian",
    first_name: "Fanni",
    ssn: "293-06-6516",
  },
  {
    department: "Business Development",
    company: "Katz",
    gender: "Non-binary",
    language: "Guaraní",
    first_name: "Marguerite",
    ssn: "219-78-1482",
  },
  {
    department: "Research and Development",
    company: "Mudo",
    gender: "Female",
    language: "Danish",
    first_name: "Emalee",
    ssn: "592-94-0093",
  },
  {
    department: "Marketing",
    company: "Rhycero",
    gender: "Male",
    language: "Tok Pisin",
    first_name: "Abdul",
    ssn: "203-81-4386",
  },
  {
    department: "Services",
    company: "Tagfeed",
    gender: "Female",
    language: "German",
    first_name: "Wendye",
    ssn: "656-57-9995",
  },
  {
    department: "Marketing",
    company: "Brightdog",
    gender: "Male",
    language: "Thai",
    first_name: "Claiborn",
    ssn: "478-55-5887",
  },
  {
    department: "Legal",
    company: "Fliptune",
    gender: "Male",
    language: "Swati",
    first_name: "Rollie",
    ssn: "656-38-8279",
  },
  {
    department: "Training",
    company: "Kayveo",
    gender: "Female",
    language: "New Zealand Sign Language",
    first_name: "Dawna",
    ssn: "760-82-8193",
  },
  {
    department: "Business Development",
    company: "Zoombox",
    gender: "Female",
    language: "Swahili",
    first_name: "Celisse",
    ssn: "209-37-1990",
  },
  {
    department: "Legal",
    company: "Bluejam",
    gender: "Male",
    language: "Burmese",
    first_name: "Konrad",
    ssn: "571-26-2635",
  },
  {
    department: "Sales",
    company: "Brainverse",
    gender: "Female",
    language: "Greek",
    first_name: "Con",
    ssn: "172-40-3537",
  },
  {
    department: "Marketing",
    company: "Kwideo",
    gender: "Female",
    language: "Chinese",
    first_name: "Anny",
    ssn: "444-60-6704",
  },
  {
    department: "Product Management",
    company: "Jaloo",
    gender: "Polygender",
    language: "Punjabi",
    first_name: "Barthel",
    ssn: "440-05-9704",
  },
  {
    department: "Sales",
    company: "Jaxworks",
    gender: "Male",
    language: "Yiddish",
    first_name: "Cosimo",
    ssn: "677-21-0935",
  },
  {
    department: "Legal",
    company: "Fivechat",
    gender: "Female",
    language: "Kyrgyz",
    first_name: "Stacey",
    ssn: "357-33-9803",
  },
  {
    department: "Engineering",
    company: "Flashdog",
    gender: "Female",
    language: "Bosnian",
    first_name: "Jaynell",
    ssn: "883-71-2482",
  },
  {
    department: "Business Development",
    company: "Livetube",
    gender: "Male",
    language: "Nepali",
    first_name: "Art",
    ssn: "656-76-1302",
  },
  {
    department: "Legal",
    company: "Zoomcast",
    gender: "Female",
    language: "Gagauz",
    first_name: "Christina",
    ssn: "406-33-4225",
  },
  {
    department: "Research and Development",
    company: "Avamm",
    gender: "Male",
    language: "Croatian",
    first_name: "Gran",
    ssn: "883-06-6385",
  },
  {
    department: "Human Resources",
    company: "Voonyx",
    gender: "Female",
    language: "Romanian",
    first_name: "Flossi",
    ssn: "781-26-9180",
  },
  {
    department: "Legal",
    company: "Flashdog",
    gender: "Female",
    language: "Indonesian",
    first_name: "Bili",
    ssn: "896-26-7637",
  },
  {
    department: "Accounting",
    company: "Realfire",
    gender: "Female",
    language: "Bulgarian",
    first_name: "Athene",
    ssn: "481-80-4077",
  },
  {
    department: "Engineering",
    company: "Pixope",
    gender: "Male",
    language: "German",
    first_name: "Gaile",
    ssn: "474-56-1678",
  },
  {
    department: "Product Management",
    company: "Devshare",
    gender: "Male",
    language: "Tamil",
    first_name: "Bertrando",
    ssn: "301-50-8150",
  },
  {
    department: "Human Resources",
    company: "Youspan",
    gender: "Male",
    language: "Dutch",
    first_name: "Reagen",
    ssn: "857-39-6065",
  },
  {
    department: "Research and Development",
    company: "Twinte",
    gender: "Female",
    language: "Telugu",
    first_name: "Taffy",
    ssn: "533-08-9583",
  },
  {
    department: "Accounting",
    company: "Tekfly",
    gender: "Male",
    language: "Dutch",
    first_name: "Erie",
    ssn: "579-22-5236",
  },
  {
    department: "Training",
    company: "Cogidoo",
    gender: "Male",
    language: "Lao",
    first_name: "Freeland",
    ssn: "636-50-5571",
  },
  {
    department: "Engineering",
    company: "Youfeed",
    gender: "Male",
    language: "Hindi",
    first_name: "Dalis",
    ssn: "305-93-0973",
  },
  {
    department: "Support",
    company: "Abata",
    gender: "Female",
    language: "Polish",
    first_name: "Katrine",
    ssn: "371-66-4671",
  },
  {
    department: "Support",
    company: "Skalith",
    gender: "Male",
    language: "Dhivehi",
    first_name: "Tucky",
    ssn: "124-28-5732",
  },
  {
    department: "Sales",
    company: "Twitterworks",
    gender: "Female",
    language: "Hiri Motu",
    first_name: "Charmine",
    ssn: "665-73-3252",
  },
  {
    department: "Sales",
    company: "Vinder",
    gender: "Male",
    language: "Kurdish",
    first_name: "Saundra",
    ssn: "411-86-8193",
  },
  {
    department: "Product Management",
    company: "Abata",
    gender: "Female",
    language: "Tswana",
    first_name: "Agnese",
    ssn: "463-64-4173",
  },
  {
    department: "Research and Development",
    company: "Demizz",
    gender: "Male",
    language: "Bengali",
    first_name: "Deck",
    ssn: "342-04-1167",
  },
  {
    department: "Services",
    company: "Devpulse",
    gender: "Female",
    language: "Icelandic",
    first_name: "Ardisj",
    ssn: "729-07-9836",
  },
  {
    department: "Training",
    company: "Myworks",
    gender: "Male",
    language: "Gujarati",
    first_name: "Theodore",
    ssn: "186-07-7459",
  },
  {
    department: "Engineering",
    company: "Mymm",
    gender: "Male",
    language: "Tajik",
    first_name: "Neron",
    ssn: "420-96-3107",
  },
  {
    department: "Accounting",
    company: "Wordtune",
    gender: "Male",
    language: "Dhivehi",
    first_name: "Filippo",
    ssn: "797-90-6177",
  },
  {
    department: "Marketing",
    company: "Kanoodle",
    gender: "Male",
    language: "Azeri",
    first_name: "Marc",
    ssn: "837-99-4084",
  },
  {
    department: "Accounting",
    company: "Zoomlounge",
    gender: "Male",
    language: "Croatian",
    first_name: "Casey",
    ssn: "498-94-4907",
  },
  {
    department: "Legal",
    company: "Einti",
    gender: "Genderfluid",
    language: "Croatian",
    first_name: "Jaquelin",
    ssn: "636-14-5561",
  },
  {
    department: "Services",
    company: "Reallinks",
    gender: "Female",
    language: "Swati",
    first_name: "Traci",
    ssn: "864-65-8577",
  },
  {
    department: "Support",
    company: "Trupe",
    gender: "Male",
    language: "English",
    first_name: "Neel",
    ssn: "424-19-7742",
  },
  {
    department: "Product Management",
    company: "Avavee",
    gender: "Male",
    language: "Finnish",
    first_name: "Tedmund",
    ssn: "560-45-3768",
  },
  {
    department: "Training",
    company: "Jaxworks",
    gender: "Female",
    language: "Afrikaans",
    first_name: "Nertie",
    ssn: "452-76-6395",
  },
  {
    department: "Business Development",
    company: "Tagopia",
    gender: "Female",
    language: "Maltese",
    first_name: "Nert",
    ssn: "406-43-6214",
  },
  {
    department: "Human Resources",
    company: "Youspan",
    gender: "Female",
    language: "Quechua",
    first_name: "Barbey",
    ssn: "656-65-6405",
  },
  {
    department: "Marketing",
    company: "Mudo",
    gender: "Male",
    language: "Burmese",
    first_name: "Fran",
    ssn: "545-39-2582",
  },
  {
    department: "Engineering",
    company: "Thoughtstorm",
    gender: "Agender",
    language: "Norwegian",
    first_name: "Farris",
    ssn: "593-52-8913",
  },
  {
    department: "Training",
    company: "Dynabox",
    gender: "Female",
    language: "Marathi",
    first_name: "Marabel",
    ssn: "703-75-4946",
  },
  {
    department: "Research and Development",
    company: "Voomm",
    gender: "Female",
    language: "Irish Gaelic",
    first_name: "Verile",
    ssn: "290-57-6945",
  },
  {
    department: "Sales",
    company: "Topiclounge",
    gender: "Male",
    language: "Japanese",
    first_name: "Tommie",
    ssn: "420-30-9509",
  },
  {
    department: "Research and Development",
    company: "Jazzy",
    gender: "Female",
    language: "Hebrew",
    first_name: "Christine",
    ssn: "206-64-2880",
  },
  {
    department: "Sales",
    company: "Realmix",
    gender: "Male",
    language: "Aymara",
    first_name: "Chrisy",
    ssn: "155-61-0302",
  },
  {
    department: "Product Management",
    company: "Reallinks",
    gender: "Bigender",
    language: "Lithuanian",
    first_name: "Vicky",
    ssn: "478-37-8543",
  },
  {
    department: "Services",
    company: "Divavu",
    gender: "Female",
    language: "Gagauz",
    first_name: "Vinny",
    ssn: "364-90-7362",
  },
  {
    department: "Services",
    company: "Oyoloo",
    gender: "Male",
    language: "Bosnian",
    first_name: "Tomkin",
    ssn: "235-48-9670",
  },
  {
    department: "Training",
    company: "Feedfish",
    gender: "Male",
    language: "Lao",
    first_name: "Shaine",
    ssn: "237-02-9029",
  },
  {
    department: "Research and Development",
    company: "Kamba",
    gender: "Male",
    language: "Dutch",
    first_name: "Hayyim",
    ssn: "431-05-1131",
  },
  {
    department: "Accounting",
    company: "Photobean",
    gender: "Genderqueer",
    language: "Kyrgyz",
    first_name: "Shandra",
    ssn: "587-05-5776",
  },
  {
    department: "Services",
    company: "Vitz",
    gender: "Male",
    language: "Dari",
    first_name: "Staffard",
    ssn: "274-40-0300",
  },
];

//1. Engineering 부서만 가져와서 콘솔 출력
const engine = data.filter((x) => x.department === "Engineering");

//2. 성별 남자이고 일본어 쓰면, 어디부서이고 이름만 가져와서 출력
const japanese = data
  .filter((x) => x.gender === "Male" && x.language === "Japanese")
  .map((x) => {
    return { deparment: x.department, first_name: x.first_name };
  });

console.log(japanese);
//3. ssn에서 맨 뒷 마지막 자리가 짝수이고, 퍼스트이름이 K,B,S로 시작하는 사람만 가져오기
const a = data.filter(
  (x) =>
    Number(x.ssn[x.ssn.length - 1]) % 2 === 0 &&
    ["K", "B", "S"].some((y) => x.first_name.startsWith(y))
);
console.log(a);

//korean,japanese,chinese 사용하고
//성별은 여성이고,
//ssn 앞의 세숫자의 합이 10이상

const b = data
  .filter(
    (x) =>
      x.language === "Korean" ||
      x.language === "Japanses" ||
      x.language === "Chinese"
  )
  .filter((x) => x.gender === "Female")
  .filter((x) => {
    // const first = x.ssn.split("-")[0];
    // return Number(first[0]) + Number(first[1]) + Number(first[2]) > 10;
    // "123-456-6789"
    const arr = [...x.ssn];
    return Number(arr[0]) + Number(arr[1]) + Number(arr[2]) > 10;
  });
console.log(b);
